FROM arm32v7/ubuntu:latest
RUN apt-get -y update && \
apt-get -y dist-upgrade && \
apt-get -y upgrade && \
apt-get install -y git vim gcc && \
apt-get update && \
apt-get install -y make gdb nano && \
git clone https://github.com/docfate111/leg.git 
